name: Qase Jest Tests - CLI Upload
on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: "Qase API URL"
        required: true
        default: "https://app.qase.io/api/v1"
      qase_report:
        description: "Enabled/disabled reporting to Qase"
        required: true
        type: boolean
      qase_project_code:
        description: "Qase project code"
        required: true
        default: "DEMO"
      qase_run_complete:
        description: "Qase Run autocomplete"
        required: true
        default: true
        type: boolean
env:
  QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
  QASE_TESTOPS_PROJECT: ${{ inputs.qase_project_code }}
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Install Qase CLI
        run: npm install -g @qaseio/qase
      - name: Set QASE_TESTOPS_RUN_COMPLETE
        run: |
          # Convert string "1" or "0" to boolean true/false
          if [ "${{ inputs.qase_run_complete }}" = "1" ]; then
            echo "QASE_TESTOPS_RUN_COMPLETE=true" >> $GITHUB_ENV
          else
            echo "QASE_TESTOPS_RUN_COMPLETE=false" >> $GITHUB_ENV
          fi
      - name: Create Qase Test Run
        run: |
          # Create a new test run and capture the run ID
          RUN_ID=$(qase run create \
            --token "$QASE_TESTOPS_API_TOKEN" \
            --project "$QASE_TESTOPS_PROJECT" \
            --title "Henrry Automated Test Run $(date +%Y-%m-%d_%H-%M-%S)" \
            --description "Triggered by GitHub Actions" | jq -r '.data.id')
          echo "QASE_TESTOPS_RUN_ID=$RUN_ID" >> $GITHUB_ENV
      - name: Run Tests
        run: npm test
      - name: Upload JUnit XML to Qase
        if: always()
        env:
          QASE_REPORT: ${{ inputs.qase_report }}
        run: |
          qase run \
            --token "$QASE_TESTOPS_API_TOKEN" \
            --project "$QASE_TESTOPS_PROJECT" \
            --run "$QASE_TESTOPS_RUN_ID" \
            --complete-run "$QASE_TESTOPS_RUN_COMPLETE" \
            --file reports/junit.xml \
            --format junit
      - name: Upload JUnit Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml
